In [17]:
import pandas as pd 
import numpy as np
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [18]:
file = 'cc_approvals.data'

cc_apps = pd.read_csv(file,header=None)

cc_apps.head()

  0      1      2  3  4  5  6     7  8  9   10 11 12     13   14 15
0  b  30.83  0.000  u  g  w  v  1.25  t  t   1  f  g  00202    0  +
1  a  58.67  4.460  u  g  q  h  3.04  t  t   6  f  g  00043  560  +
2  a  24.50  0.500  u  g  q  h  1.50  t  f   0  f  g  00280  824  +
3  b  27.83  1.540  u  g  w  v  3.75  t  t   5  t  g  00100    3  +
4  b  20.17  5.625  u  g  w  v  1.71  t  f   0  f  s  00120    0  +

In [19]:
cc_apps.tail(20)

    0      1       2  3  4   5   6      7  8  9   10 11 12     13   14 15
670  b  47.17   5.835  u  g   w   v  5.500  f  f   0  f  g  00465  150  -
671  b  25.83  12.835  u  g  cc   v  0.500  f  f   0  f  g  00000    2  -
672  a  50.25   0.835  u  g  aa   v  0.500  f  f   0  t  g  00240  117  -
673  ?  29.50   2.000  y  p   e   h  2.000  f  f   0  f  g  00256   17  -
674  a  37.33   2.500  u  g   i   h  0.210  f  f   0  f  g  00260  246  -
675  a  41.58   1.040  u  g  aa   v  0.665  f  f   0  f  g  00240  237  -
676  a  30.58  10.665  u  g   q   h  0.085  f  t  12  t  g  00129    3  -
677  b  19.42   7.250  u  g   m   v  0.040  f  t   1  f  g  00100    1  -
678  a  17.92  10.210  u  g  ff  ff  0.000  f  f   0  f  g  00000   50  -
679  a  20.08   1.250  u  g   c   v  0.000  f  f   0  f  g  00000    0  -
680  b  19.50   0.290  u  g   k   v  0.290  f  f   0  f  g  00280  364  -
681  b  27.83   1.000  y  p   d   h  3.000  f  f   0  f  g  00176  537  -
682  b  17.08   3.290  u  g   i   v  0.335  f  f   0  t  g  00140    2  -
683  b  36.42   0.750  y  p   d   v  0.585  f  f   0  f  g  00240    3  -
684  b  40.58   3.290  u  g   m   v  3.500  f  f   0  t  s  00400    0  -
685  b  21.08  10.085  y  p   e   h  1.250  f  f   0  f  g  00260    0  -
686  a  22.67   0.750  u  g   c   v  2.000  f  t   2  t  g  00200  394  -
687  a  25.25  13.500  y  p  ff  ff  2.000  f  t   1  t  g  00200    1  -
688  b  17.92   0.205  u  g  aa   v  0.040  f  f   0  f  g  00280  750  -
689  b  35.00   3.375  u  g   c   h  8.290  f  f   0  t  g  00000    0  -

In [20]:
cc_apps = cc_apps.replace('?',np.nan)

In [21]:
cc_apps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       678 non-null    object
 1   1       678 non-null    object
 2   2       690 non-null    float64
 3   3       684 non-null    object
 4   4       684 non-null    object
 5   5       681 non-null    object
 6   6       681 non-null    object
 7   7       690 non-null    float64
 8   8       690 non-null    object
 9   9       690 non-null    object
 10  10      690 non-null    int64
 11  11      690 non-null    object
 12  12      690 non-null    object
 13  13      677 non-null    object
 14  14      690 non-null    int64
 15  15      690 non-null    object
dtypes: float64(2), int64(2), object(12)
memory usage: 86.4+ KB

In [22]:
numeric_cols = cc_apps.select_dtypes(include=['int64', 'float64']).columns
categorical_cols = cc_apps.select_dtypes(include='object').columns

num_imputer = KNNImputer()
cat_imputer = SimpleImputer(strategy='most_frequent')

cc_apps[numeric_cols] = num_imputer.fit_transform(cc_apps[numeric_cols])
cc_apps[categorical_cols] = cat_imputer.fit_transform(cc_apps[categorical_cols])

cc_apps.isna().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
dtype: int64

In [23]:
label_encoder = LabelEncoder()

for col in cc_apps.columns:
    if cc_apps[col].dtype =='object':
        cc_apps[col]= label_encoder.fit_transform(cc_apps[col])

In [24]:
df = cc_apps.drop(cc_apps.columns[[10,12]],axis=1)

In [25]:
df

     0    1       2   3   4   5   6     7   8   9   11  13     14  15
0     1  156   0.000   1   0  12   7  1.25   1   1   0  68    0.0   0
1     0  328   4.460   1   0  10   3  3.04   1   1   0  11  560.0   0
2     0   89   0.500   1   0  10   3  1.50   1   0   0  96  824.0   0
3     1  125   1.540   1   0  12   7  3.75   1   1   1  31    3.0   0
4     1   43   5.625   1   0  12   7  1.71   1   0   0  37    0.0   0
..   ..  ...     ...  ..  ..  ..  ..   ...  ..  ..  ..  ..    ...  ..
685   1   52  10.085   2   2   4   3  1.25   0   0   0  90    0.0   1
686   0   71   0.750   1   0   1   7  2.00   0   1   1  67  394.0   1
687   0   97  13.500   2   2   5   2  2.00   0   1   1  67    1.0   1
688   1   20   0.205   1   0   0   7  0.04   0   0   0  96  750.0   1
689   1  197   3.375   1   0   1   3  8.29   0   0   1   0    0.0   1

[690 rows x 14 columns]

In [26]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [27]:
x_train , x_test , y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [28]:
scaler = MinMaxScaler(feature_range=(0,1))

rescaledX_train = scaler.fit_transform(x_train)
rescaledX_test = scaler.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, fbeta_score, classification_report

In [47]:
models = {
    "LogisticRegression": LogisticRegression(solver='liblinear', max_iter=100),
    "KNN": KNeighborsClassifier(),
    "SVC": SVC(),
    "DecisionTree": DecisionTreeClassifier(),
    "RandomForest": RandomForestClassifier(),
    "NaiveBayes": GaussianNB()
}

In [48]:
for name, model in models.items():
    print(f'{name} \n--------------')
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print(f'Training Accuracy: {accuracy_score(y_train, model.predict(x_train))}')
    print(f'Testing Accuracy: {accuracy_score(y_test, y_pred)}')
    print(f'Testing Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}')
    print(f'Testing Recall: {recall_score(y_test, y_pred)}')    
    print(f'Testing Precesion: {precision_score(y_test, y_pred)}')
    print(f'Testing F-1: {f1_score(y_test, y_pred)}')
    print(f'Testing F-Beta: {fbeta_score(y_test, y_pred, beta=0.5)}')
    print('-'*30)
    print(' ')

LogisticRegression
--------------
Training Accuracy: 0.8571428571428571
Testing Accuracy: 0.8377192982456141
Testing Confusion Matrix:
[[92 11]
 [26 99]]
Testing Recall: 0.792
Testing Precesion: 0.9
Testing F-1: 0.8425531914893617
Testing F-Beta: 0.8761061946902655
------------------------------

KNN
--------------
Training Accuracy: 0.7770562770562771
Testing Accuracy: 0.6578947368421053
Testing Confusion Matrix:
[[59 44]
 [34 91]]
Testing Recall: 0.728
Testing Precesion: 0.674074074074074
Testing F-1: 0.7
Testing F-Beta: 0.6842105263157895
------------------------------

SVC
--------------
Training Accuracy: 0.6558441558441559
Testing Accuracy: 0.6403508771929824
Testing Confusion Matrix:
[[ 28  75]
 [  7 118]]
Testing Recall: 0.944
Testing Precesion: 0.6113989637305699
Testing F-1: 0.7421383647798742
Testing F-Beta: 0.6577480490523969
------------------------------

DecisionTree
--------------
Training Accuracy: 1.0
Testing Accuracy: 0.8026315789473685
Testing Confusion Matrix:
[[ 78  25]
 [ 20 105]]
Testing Recall: 0.84
Testing Precesion: 0.8076923076923077
Testing F-1: 0.8235294117647058
Testing F-Beta: 0.813953488372093
------------------------------

RandomForest
--------------
Training Accuracy: 1.0
Testing Accuracy: 0.8596491228070176
Testing Confusion Matrix:
[[ 91  12]
 [ 20 105]]
Testing Recall: 0.84
Testing Precesion: 0.8974358974358975
Testing F-1: 0.8677685950413223
Testing F-Beta: 0.8853288364249579
------------------------------

NaiveBayes
--------------
Training Accuracy: 0.8246753246753247
Testing Accuracy: 0.7807017543859649
Testing Confusion Matrix:
[[ 66  37]
 [ 13 112]]
Testing Recall: 0.896
Testing Precesion: 0.7516778523489933
Testing F-1: 0.8175182481751825
Testing F-Beta: 0.7766990291262136
------------------------------